# Generated by Django 4.1.7 on 2023-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='3.png', null=True, upload_to='images'),
        ),
    ]
